[project]
name = "star-discovery"
authors = [{name = "Peter Snyder", email = "pes@brave.com"}]
license = "MIT"
readme = "README.md"
version = "0.0.2"
dependencies = [
    "beautifulsoup4",
    "packaging",
    "tabulate"
]

[project.optional-dependencies]
dev = [
    "black",
    "mypy",
    "pylint",
    "types-tabulate"
]

[tool.black]
line-length = 88

[tool.setuptools.packages.find]
where = ['src']

[project.scripts]
star-discovery = "star_discovery.cli.parser:run"
